### ISSUE TITLE
Error opening website

### ISSUE THREAD

**Issue by pgillett** [exceptionnotfound/BlazorGames#1]
The blazorgames.net site is not opening. Getting a Blazor error first. If you click the Reload link it goes into a circular refresh adding an ever increasing query string "...~q=p=/~and~q=p=/~and~q=p=/~and~q=p=" to the address bar.

Seen this before, but can't recall exactly what caused it (or more to the point what fixed it), but our issues were around the base href and nojekyll,

**Comment by exceptionnotfound** [comment]
I believe I have corrected this issue. Was trying to get this to work on GitHub pages so the direct links would work, but no luck.
