### ISSUE TITLE
Tetris standardDelay bug

### ISSUE THREAD

**Issue by Jadaw1n** [exceptionnotfound/BlazorGames#8]
Hi there
The level progression function has a bug in it. From level 5 the blocks start dropping right away...
The offending line:
https://github.com/exceptionnotfound/BlazorGames/blob/6f2e934de7e3deb26b4cedfd41da16971b3f75f3/BlazorGames/Pages/Tetris.razor#L179

What you actually want to do is just `standardDelay = standardDelay - 100` (as per your comment).

The problem with that is you still can't progress past level 10, since then the delay will be 0. Maybe do something like  `standardDelay = standardDelay * 0.8` to have the game go faster without ever reaching 0.

**Comment by exceptionnotfound** [comment]
I've corrected the code to be more representative of what I actually want:

`standardDelay = 1000 - ((newLevel - 1) * 100);`

Thanks for letting me know!
