### ISSUE TITLE
Drag-drop issue on Firefox v89

### ISSUE THREAD

**Issue by conficient** [exceptionnotfound/BlazorGames#9]
Trying out Solitaire on Firefox (v89, 64-bit on Windows 10).

If you drag a card from one stack to another it changes to displaying the card image (e.g. https://blazorgames.net/images/common/cardClubsFive.png)

Fine on Chrome and Edge

**Comment by exceptionnotfound** [comment]
Fixed by adding stopPropagation and preventDefault for onDrop events. Thanks for catching this!
